version: "3.5"
services:
  gomq:
    container_name: gomq
    image: gomq/gomq:v1
    ports:
      - "9000:9000"
      - "8000:8000"
      - "6060:6060"
    volumes:
      - "/Volumes/gomq/:/var/log/gomq/"
    networks:
      - mqnet
    depends_on:
      - etcd

  etcd:
    container_name: etcd
    hostname: etcd
    image: bitnami/etcd:3
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
      - "7001:7001"
    volumes:
      - "/Volumes/etcd/data:/opt/bitnami/etcd/data"
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"
      - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
    networks:
      - mqnet

networks:
  mqnet:
    driver: bridge
